# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Vivado/Pipeline_CPU/file/icf-v-p.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet
